import json
import os
from typing import Annotated, TypedDict, List
#Semantics memory storage
import chromadb
from chromadb.utils import embedding_functions
#Orchestrator
from langgraph.graph import StateGraph, START, END

from fastapi.staticfiles import StaticFiles
from google import genai
from google.genai import types
from dotenv import load_dotenv

load_dotenv(".env")
chroma_client = chromadb.Client()

def prose_agent(state: AgentState):
    # Use the client directly, specify the model string here
    response = client.models.generate_content(
        model="gemini-2.0-flash", 
        contents=f"Context: {state['plot_context']}\nTask: {state['messages'][-1]}"
    )
    return {"messages": [response.text]}


#Chatbot Management Through useStates similar
class AgentState(TypedDict):
    messages: List[str]
    plot_context: str
    revision_needed: bool

#
class StoryMemory:
    def __init__(self):
        self.client = chromadb.PersistentClient(path="./chroma_db")
        self.ef = embedding_functions.GoogleGeminiEmbeddingFunction(
            api_key=os.getenv("GEMINI_API_KEY")
        )
        self.collection = self.client.get_or_create_collection(
            name="plot_notes", 
            embedding_function=self.ef
        )

    def query_context(self, text: str):
        results = self.collection.query(query_texts=[text], n_results=2)
        return " ".join(results['documents'][0])


client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

def prose_agent(state: AgentState):
    """Suggestor"""
    response = client.models.generate_content(
        model="gemini-2.0-flash",
        contents=f"Context: {state['plot_context']}\nTask: {state['messages'][-1]}",
        config=types.GenerateContentConfig(system_instruction="")
    )
    return {"messages": [response.text]}

def critic_agent(state: AgentState):
    """Editor."""
    # How to determine what is considered plotholes?
    return {"revision_needed": False} 

def ask_chatbot(user_message: str, plot_context: str = ""):
    # Initialize the state for the graph
    initial_state = {
        "messages": [user_message],
        "plot_context": plot_context,
        "revision_needed": False
    }
    
    # Run the LangGraph workflow
    result = app.invoke(initial_state)
    
    # Return the last message generated by the agents
    return result["messages"][-1]

# The Workflows
workflow = StateGraph(AgentState)

workflow.add_node("writer", prose_agent)
workflow.add_node("editor", critic_agent)

workflow.add_edge(START, "writer")
workflow.add_edge("writer", "editor")
workflow.add_edge("editor", END)

app = workflow.compile()